### ISSUE TITLE
Module Support Requests- Token Action HUD/Drag Ruler

### ISSUE THREAD

**Issue by justinthejaguar** [foundryvtt-dcc/dcc-content#15] opened 2021-04-20 12:27 UTC
I would like to request support for two modules that I believe will speed up combat (particularly on the Judge's side).

Token Action HUD https://foundryvtt.com/packages/token-action-hud/ - Esposito is working to make it more modular for use with other systems since he doesn't have the time he has in the past to update it for every system. This will cut the amount of time the Judge (and Level 0 characters) need to have character sheets open, being able to trigger attacks directly from the token.

Drag Ruler https://foundryvtt.com/packages/drag-ruler - This module will make it easier for the Judge to remember how far monster's move is as well as remind players how far they are able to move if they decide to go a'slashin' with their halfling moneylender.

**Comment by mooped** [comment] 2021-04-29 21:46
Drag Ruler now implements DCC support - edited the description to indicate that Token Action HUD still needs investigation.

**Comment by justinthejaguar** [comment] 2021-05-02 00:33
It looks like Espositos has added information on how to allow support for Token Action HUD. Does this help on your end? https://github.com/espositos/fvtt-tokenactionhud/blob/master/adding_systems.md

**Comment by cyface** [comment] 2021-12-29 15:54
Closing this issue, since it is now a duplicate of: https://github.com/foundryvtt-dcc/dcc/issues/195

**Closed by cyface** 2021-12-29 15:54 UTC
